// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARu85cuyyUDxp3sKNxNJCgoBQlwN3n3l0',
    appId: '1:292083503007:web:ce0710edc4879aa35f37aa',
    messagingSenderId: '292083503007',
    projectId: 'projectmobile-a923d',
    authDomain: 'projectmobile-a923d.firebaseapp.com',
    storageBucket: 'projectmobile-a923d.appspot.com',
    measurementId: 'G-TEPFRCVGPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-sanSVwgN_1hWsJn8KG8fd2tt5Vrn0o',
    appId: '1:292083503007:android:9d0ee5d7fb079f545f37aa',
    messagingSenderId: '292083503007',
    projectId: 'projectmobile-a923d',
    storageBucket: 'projectmobile-a923d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYOFGYE8Vr0XZ0rFZLauQjYO49UEdlFxY',
    appId: '1:292083503007:ios:81161c2378a6be7c5f37aa',
    messagingSenderId: '292083503007',
    projectId: 'projectmobile-a923d',
    storageBucket: 'projectmobile-a923d.appspot.com',
    iosBundleId: 'com.example.educationApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYOFGYE8Vr0XZ0rFZLauQjYO49UEdlFxY',
    appId: '1:292083503007:ios:81161c2378a6be7c5f37aa',
    messagingSenderId: '292083503007',
    projectId: 'projectmobile-a923d',
    storageBucket: 'projectmobile-a923d.appspot.com',
    iosBundleId: 'com.example.educationApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARu85cuyyUDxp3sKNxNJCgoBQlwN3n3l0',
    appId: '1:292083503007:web:d93b54d9fa5190695f37aa',
    messagingSenderId: '292083503007',
    projectId: 'projectmobile-a923d',
    authDomain: 'projectmobile-a923d.firebaseapp.com',
    storageBucket: 'projectmobile-a923d.appspot.com',
    measurementId: 'G-W3Z372K733',
  );

}